### ISSUE TITLE
[SOLVED] [Bug] wasptool doesn't find PineTime

### ISSUE THREAD

**Issue by Tuxilio** [wasp-os/wasp-os#514]
(discussion started in Matrix chat)

I just installed wasp-os 0.4 and followed the guide about writing a first app. When I try to upload it using wasptool (tried with 0.4 and master branch), the message comes:

```
tuxilio@ice-pad > ~/Programme/PineTime/wasp-os > master >> tools/wasptool \
        --exec docs/hello.py \
        --eval "wasp.system.register(HelloApp())"
ERROR: Cannot find suitable wasp-os device
~~~
Scanning...
~~~
```
```
tuxilio@ice-pad > ~/Programme/PineTime/wasp-os > master > sudo hcitool lescan
LE Scan ...
D0:03:DF:91:3C:4F (unknown)
CB:08:1E:3E:2B:59 PineTime
CB:08:1E:3E:2B:59 (unknown)
01:35:5D:C0:7D:15 (unknown)
77:7B:20:D0:C8:4E (unknown)
9C:3E:53:0F:68:87 (unknown)
9C:3E:53:0F:68:87 (unknown)
^C
```
```
tuxilio@ice-pad > ~/Programme/PineTime/wasp-os > master > tools/wasptool --device CB:08:1E:3E:2B:59 --console
Traceback (most recent call last):
  File "/home/tuxilio/Programme/PineTime/wasp-os/tools/wasptool", line 447, in <module>
    console.expect(r'Connect.*\(([0-9A-F:]*)\)')
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 354, in expect
    return self.expect_list(compiled_pattern_list,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 383, in expect_list
    return exp.expect_loop(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 179, in expect_loop
    return self.eof(e)
           ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 122, in eof
    raise exc
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0x7fc87a7affb0>
command: tools/pynus/pynus.py
args: [b'tools/pynus/pynus.py', b'--address', b'CB:08:1E:3E:2B:59']
buffer (last 100 chars): ''
before (last 100 chars): 'ecurity policy blocked the reply, the reply timeout expired, or the network connection was broken.\r\n'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: None
flag_eof: True
pid: 4501
child_fd: 5
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: <_io.StringIO object at 0x7fc87a9cda80>
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile('Connect.*\\(([0-9A-F:]*)\\)')
```
```
tuxilio@ice-pad > ~/Programme/PineTime/wasp-os > master > tools/wasptool --device "CB:08:1E:3E:2B:59" --console
ERROR: Cannot find suitable wasp-os device
~~~
Scanning...
~~~

```

So I installes master branch micropython.zip, but that doesn't help:

 
```
tuxilio@ice-pad > ~/Programme/PineTime/wasp-os > master ± > tools/wasptool --device CB:08:1E:3E:2B:59 --console        
Traceback (most recent call last):
  File "/home/tuxilio/Programme/PineTime/wasp-os/tools/wasptool", line 447, in <module>
    console.expect(r'Connect.*\(([0-9A-F:]*)\)')
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 354, in expect
    return self.expect_list(compiled_pattern_list,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 383, in expect_list
    return exp.expect_loop(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 179, in expect_loop
    return self.eof(e)
           ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 122, in eof
    raise exc
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0x7f8a353506b0>
command: tools/pynus/pynus.py
args: [b'tools/pynus/pynus.py', b'--address', b'CB:08:1E:3E:2B:59']
buffer (last 100 chars): ''
before (last 100 chars): 'ecurity policy blocked the reply, the reply timeout expired, or the network connection was broken.\r\n'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: None
flag_eof: True
pid: 7854
child_fd: 5
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: <_io.StringIO object at 0x7f8a353b1a80>
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile('Connect.*\\(([0-9A-F:]*)\\)')
```

I'm on Debian Unstable.

any ideas?

**Comment by GaryM0101** [comment]
Not a wasp-os issue, you need to bind the pinetime mac address with Debian BLE services using bluetoothctl or other.

**Comment by fgaz** [comment]
Is bluez installed? What's the full output of `tools/pynus/pynus.py --address CB:08:1E:3E:2B:59`?

**Comment by GaryM0101** [comment]
So I've gotten the "org.bluez.Error.AuthenticationFailed" today after a power outage. Wasptool fails to connect. 

pi@raspberrypi:~/wasp-os $ bluetoothctl pair FC:16:5F:3E:8E:7C
Attempting to pair with FC:16:5F:3E:8E:7C
[CHG] Device FC:16:5F:3E:8E:7C Connected: yes
Failed to pair: org.bluez.Error.AuthenticationFailed

Running "sudo systemctl status bluetooth.service" shows the daemon trying to connect to the mac address, the queue is filling up and stuck.

pi@raspberrypi:~/wasp-os $ sudo systemctl status bluetooth.service
● bluetooth.service - Bluetooth service
   Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset
   Active: active (running) since Mon 2024-09-30 16:17:06 PDT; 1 day 15h ago
     Docs: man:bluetoothd(8)
 Main PID: 509 (bluetoothd)
   Status: "Running"
    Tasks: 1 (limit: 3596)
   CGroup: /system.slice/bluetooth.service
           └─509 /usr/lib/bluetooth/bluetoothd

Oct 02 08:01:54 raspberrypi bluetoothd[509]: ATT bt_io_connect(FC:16:5F:3E:8E:7C
Oct 02 08:02:00 raspberrypi bluetoothd[509]: ATT bt_io_connect(FC:16:5F:3E:8E:7C
Oct 02 08:03:02 raspberrypi bluetoothd[509]: ATT bt_io_connect(FC:16:5F:3E:8E:7C
Oct 02 08:03:30 raspberrypi bluetoothd[509]: ATT bt_io_connect(FC:16:5F:3E:8E:7C
Oct 02 08:03:35 raspberrypi bluetoothd[509]: ATT bt_io_connect(FC:16:5F:3E:8E:7C
Oct 02 08:04:31 raspberrypi bluetoothd[509]: ATT bt_io_connect(FC:16:5F:3E:8E:7C
Oct 02 08:04:42 raspberrypi bluetoothd[509]: ATT bt_io_connect(FC:16:5F:3E:8E:7C
Oct 02 08:05:03 raspberrypi bluetoothd[509]: ATT bt_io_connect(FC:16:5F:3E:8E:7C
Oct 02 08:05:12 raspberrypi bluetoothd[509]: ATT bt_io_connect(FC:16:5F:3E:8E:7C
Oct 02 08:05:41 raspberrypi bluetoothd[509]: ATT bt_io_connect(FC:16:5F:3E:8E:7C

Running  "sudo hciconfig hci0 down; systemctl restart bluetooth" seems to solve the issue. 

pi@raspberrypi:~/wasp-os $ sudo hciconfig hci0 down; systemctl restart bluetooth
pi@raspberrypi:~/wasp-os $ ./tools/wasptool --console
Connected to PineTime (FC:16:5F:3E:8E:7C).
Exit console using Ctrl-X.
>>>

However this might only be related to Debian so doing a doc change wouldn't apply to all flavors. 
Thoughts?

**Comment by GaryM0101** [comment]
Okay, I'll get a PR going, thanks!
